### ISSUE TITLE
Add modifier keybinds

### ISSUE THREAD

**Issue by masudhossain** [martpie/react-keybinding-component#8]
We want to add keybinds with modifiers like shift, ctl, etc 

How can we do this?

**Comment by masudhossain** [comment]
Also, the keybinds executes if it's typed on tiptap editor, which A LOT of people use now.

**Comment by martpie** [comment]
> Also, the keybinds executes if it's typed on tiptap editor, which A LOT of people use now.

Have you tried the `preventInputConflict` property?

> Shift, Alt, Ctrl

So, in theory, those are easy to make and I can build the feature.

The problem comes if you need to differentiate platforms like macOS and windows, where in macOS, CMD is the default modifier key, but on Linux/Windows, it's Ctrl.

The same apply for the Alt key, which is the option key on Mac.

What would be your expectation here?

**Comment by masudhossain** [comment]
I believe this is a common way people go about it when keybinding.  

So alt on Mac should be option and CTRL on Mac should be command. 

I'll try that prop to see if it works with tiptap. Really loving this library! Def the simplest and easiest so far.

**Comment by masudhossain** [comment]
Tried it, but still executes. I believe it might happen only in tiptap editors. And tiptap doesn't use <input> or <textarea>. 
![image](https://github.com/martpie/react-keybinding-component/assets/16615124/9ed6a1d3-0aba-41f2-8aa1-fbab25eb8935)

`<KeyBinding onKey={(e) => { e.key === ((index + 1).toString()) && history.push(`${project.project_access_type === "Client" ? "/portal" : ""}/o/${project.organization.token}/projects/${project.token}/tasks`) }} preventInputConflict={true}/>`

**Comment by martpie** [comment]
Ok, I just had a look, and they seem to be using `contenteditable=true` on their HTML element. 

I guess we could look if the body's `activeElement` has a parent with this HTML attribute, but I worry about performance, so we could make it disabled by default, and enabled via a prop. 

> So alt on Mac should be option and CTRL on Mac should be command.

I need to do more research, because there is no nice standard to identify platforms on the browers, so listening for `e.metaKey` might be not consistent or not working well.

**Comment by masudhossain** [comment]
> Ok, I just had a look, and they seem to be using `contenteditable=true` on their HTML element.
> 
> I guess we could look if the body's `activeElement` has a parent with this HTML attribute, but I worry about performance, so we could make it disabled by default, and enabled via a prop.
> 
> > So alt on Mac should be option and CTRL on Mac should be command.
> 
> I need to do more research, because there is no nice standard to identify platforms on the browers, so listening for `e.metaKey` might be not consistent or not working well.

I appreciate that! Would really love to use this library to add keybinding all over our platform :)

**Comment by martpie** [comment]
2.2.0 should fix the conflict with tiptap once you enable the `preventContentEditableConflict` prop. Regarding modifiers, let's move the discussion to #1 :)

**Comment by masudhossain** [comment]
Legend!
